# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Feed-Amalgamator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Directory
        run: mkdir configuration
      - name: Setup Config Files
        env:
          TEST_SECRET: ${{secrets.TEST_CONFIG}}
          APP_SECRET: ${{secrets.APP_CONFIG}}
        shell: bash
        run: |
            echo "$APP_SECRET" >> configuration/app_settings.ini
            echo "$TEST_SECRET" >> configuration/test_mastodon_client_info.ini
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11.5"
      - name: Install dependencies
        run: |
          pdm init -gn
          pdm install 
          pdm list

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Feed-Amalgamator'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5AD2BC11A9074758B016058EE3BE7AED }}
